spring:
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/dev_dojo?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_MYSQL_ROOT_USERNAME}
    password: ${ENV_MYSQL_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    com.example.dev_dojo: debug

server:
  port: 8090
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20


#database:
#  url: ${DB_URL:localhost}:${DB_PORT:3306}
#  username: ${LOCAL_USERNAME:fuzari}
#  password: ${LOCAL_PASSWORD:123}