spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    com.example.dev_dojo: debug

server:
  port: 8090
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

database:
  url: ${DB_URL:localhost}:${DB_PORT:3306}
  username: ${LOCAL_USERNAME:fuzari}
  password: ${LOCAL_PASSWORD:123}