spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: users-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_MYSQL_ROOT_USERNAME:root}
    password: ${ENV_MYSQL_ROOT_PASSWORD:root}
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.example.users-microservice: debug
    org.hibernate.orm.jdbc.bind: trace
#    net.ttddyy.dsproxy.listener: debug
server:
  port: 8060
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20